FROM php:7.4.33-fpm-alpine

# 7.4.33  	xdebug-2.9.8
# 8.2.5     xdebug-3.2.1    

WORKDIR /usr/src/php/ext/

# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
RUN apk update \
    && docker-php-source extract \
    && wget https://pecl.php.net/get/xdebug-2.9.8.tgz \
    && tar zxvf xdebug-2.9.8.tgz \
    && mv xdebug-2.9.8 xdebug \
    && rm -f xdebug-2.9.8.tgz \
    && docker-php-ext-install mysqli && docker-php-ext-enable mysqli \
    && docker-php-ext-install pdo && docker-php-ext-enable pdo \
    && docker-php-ext-install pdo_mysql && docker-php-ext-enable pdo_mysql \
    && docker-php-ext-install xdebug && docker-php-ext-enable xdebug \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_port=9001" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_host=host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

WORKDIR /app
VOLUME [ "/app" ]

ENV TZ=Asia/Shanghai
# RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai'>/etc/timezone

EXPOSE 9000 9001
#CMD ["php", "-S", "0.0.0.0:9000", "-t", "/app"]
