version: '3'

services:
  ensoul-nav:
    image: findstay/ensoul-nav:latest
    container_name: ensoul-nav
    privileged: true
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - './:/var/www/html'
    environment:
      TZ: Asia/Shanghai

